version: 2.1

jobs:
  build:
    machine:
      enabled: true
      image: ubuntu-1604:202007-01
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - checkout
      - run:
          name: Build image
          command: |
            echo "Nevermind CircleCI doesn't support ARM builds yet"
            # docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_ACCESS_TOKEN
            # VERSION=${CIRCLE_TAG:-latest}
            # docker buildx create --name cci-builder --use
            # docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --load -t patoarvizu/stwr:$CIRCLE_SHA1 .
            # docker tag patoarvizu/stwr:$CIRCLE_SHA1 patoarvizu/stwr:latest
            # docker tag patoarvizu/stwr:$CIRCLE_SHA1 patoarvizu/stwr:$VERSION
            # docker push patoarvizu/stwr:$CIRCLE_SHA1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: authentication-tokens
          filters:
            tags:
              only: /^v\d+\.\d+.\d+$/